package com.myapp.struts;
// Generated Jun 27, 2015 11:29:21 AM by Hibernate Tools 3.2.1.GA



/**
 * Admin generated by hbm2java
 */
public class Admin extends org.apache.struts.action.ActionForm implements java.io.Serializable {


     private String username;
     private String password;
     private String mail;

    public Admin() {
    }

	
    public Admin(String username) {
        this.username = username;
    }
    public Admin(String username, String password, String mail) {
       this.username = username;
       this.password = password;
       this.mail = mail;
    }
   
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getMail() {
        return this.mail;
    }
    
    public void setMail(String mail) {
        this.mail = mail;
    }




}


