package com.myapp.struts;
// Generated Jun 27, 2015 11:29:21 AM by Hibernate Tools 3.2.1.GA



/**
 * Booking generated by hbm2java
 */
public class Booking extends org.apache.struts.action.ActionForm implements java.io.Serializable {


     private int tid;
     private Passenger passenger;
     private String cardtype;
     private String emonth;
     private String eyear;
     private String cardno;
     private String fullname;
     private int age;
     private String gender;
     private int bkfid;
     private int wanted;
     private String name;

    public Booking() {
    }

	
    public Booking(int tid) {
        this.tid = tid;
    }
    public Booking(int tid, Passenger passenger, String cardtype, String emonth, String eyear, String cardno, String fullname, int age, String gender) {
       this.tid = tid;
       this.passenger = passenger;
       this.cardtype = cardtype;
       this.emonth = emonth;
       this.eyear = eyear;
       this.cardno = cardno;
       this.fullname = fullname;
       this.age = age;
       this.gender = gender;
    }
   
    public int getTid() {
        return this.tid;
    }
    
    public void setTid(int tid) {
        this.tid = tid;
    }
    public Passenger getPassenger() {
        return this.passenger;
    }
    
    public void setPassenger(Passenger passenger) {
        this.passenger = passenger;
    }
    public String getCardtype() {
        return this.cardtype;
    }
    
    public void setCardtype(String cardtype) {
        this.cardtype = cardtype;
    }
    public String getEmonth() {
        return this.emonth;
    }
    
    public void setEmonth(String emonth) {
        this.emonth = emonth;
    }
    public String getEyear() {
        return this.eyear;
    }
    
    public void setEyear(String eyear) {
        this.eyear = eyear;
    }
    public String getCardno() {
        return this.cardno;
    }
    
    public void setCardno(String cardno) {
        this.cardno = cardno;
    }
    public String getFullname() {
        return this.fullname;
    }
    
    public void setFullname(String fullname) {
        this.fullname = fullname;
    }
    public int getAge() {
        return this.age;
    }
    
    public void setAge(int age) {
        this.age = age;
    }
    public String getGender() {
        return this.gender;
    }
    
    public void setGender(String gender) {
        this.gender = gender;
    }

    /**
     * @return the bkfid
     */
    public int getBkfid() {
        return bkfid;
    }

    /**
     * @param bkfid the bkfid to set
     */
    public void setBkfid(int bkfid) {
        this.bkfid = bkfid;
    }

    /**
     * @return the wanted
     */
    public int getWanted() {
        return wanted;
    }

    /**
     * @param wanted the wanted to set
     */
    public void setWanted(int wanted) {
        this.wanted = wanted;
    }

    /**
     * @return the name
     */
    public String getName() {
        return name;
    }

    /**
     * @param name the name to set
     */
    public void setName(String name) {
        this.name = name;
    }




}


