package com.myapp.struts;
// Generated Jun 27, 2015 11:29:21 AM by Hibernate Tools 3.2.1.GA



/**
 * Flight generated by hbm2java
 */
public class Flight extends org.apache.struts.action.ActionForm implements java.io.Serializable {


     private int fid;
     private String fname;
     private String departure;
     private String arrival;
     private int seats;
     private double price;
     private int day;
     private String duration;
     private String fromloc;
     private String toloc;
     private int bseats;

    public Flight() {
    }

	
    public Flight(int fid) {
        this.fid = fid;
    }
    public Flight(int fid, String fname, String departure, String arrival, int seats, double price, int day, String duration, String fromloc, String toloc) {
       this.fid = fid;
       this.fname = fname;
       this.departure = departure;
       this.arrival = arrival;
       this.seats = seats;
       this.price = price;
       this.day = day;
       this.duration = duration;
       this.fromloc = fromloc;
       this.toloc = toloc;
    }
   
    public int getFid() {
        return this.fid;
    }
    
    public void setFid(int fid) {
        this.fid = fid;
    }
    public String getFname() {
        return this.fname;
    }
    
    public void setFname(String fname) {
        this.fname = fname;
    }
    public String getDeparture() {
        return this.departure;
    }
    
    public void setDeparture(String departure) {
        this.departure = departure;
    }
    public String getArrival() {
        return this.arrival;
    }
    
    public void setArrival(String arrival) {
        this.arrival = arrival;
    }
    public int getSeats() {
        return this.seats;
    }
    
    public void setSeats(int seats) {
        this.seats = seats;
    }
    public double getPrice() {
        return this.price;
    }
    
    public void setPrice(double price) {
        this.price = price;
    }
    public int getDay() {
        return this.day;
    }
    
    public void setDay(int day) {
        this.day = day;
    }
    public String getDuration() {
        return this.duration;
    }
    
    public void setDuration(String duration) {
        this.duration = duration;
    }
    public String getFromloc() {
        return this.fromloc;
    }
    
    public void setFromloc(String fromloc) {
        this.fromloc = fromloc;
    }
    public String getToloc() {
        return this.toloc;
    }
    
    public void setToloc(String toloc) {
        this.toloc = toloc;
    }

    /**
     * @return the bseats
     */
    public int getBseats() {
        return bseats;
    }

    /**
     * @param bseats the bseats to set
     */
    public void setBseats(int bseats) {
        this.bseats = bseats;
    }




}


